ower_good_data = [
    {'link': 'https://soft.reelly.io/project/general?projectid=440', 'name': 'Golf Views', 'area': 'Emaar South',
     'devel': 'Emaar', 'price': '1140000', 'date': 'AUG 2023',
     'image': ['https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/U4sqB476BZJEwoLGSm50waxrFEQ/9jLZ2w../2.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/k3Em_OO-0mStKTVAsP61Hk5OV70/YoQglw../3.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/wAUTDaG98wQpe-O9YeXczclXjhg/PMRl2w../4.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/sZDBbVFzPNWhr0MGve6rAsuGsXM/HfmiVg../5.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/1IFxiBWcJlt8XnXaAowOEjq59bg/h0jfAA../0.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/2uM5fXuHB_NXlzTKUOm7gvDyA64/UijStw../1.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/nM3W3eFmqO4lRAL8PdmVDE4vR4k/qoueZw../Bathroom_View01.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/ZZY_41_oUuOpLPrhhg0MCTws52M/0BEd2g../Bathroom_View02.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/MNUWiLMZpouKkWUoABNYaK_vHM4/Gcd8zw../2BR+Living+View01.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/r2pI3ge7NL7WysMfwBE8i4yffBI/demo7w../2BR+Living+View02bigger.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/WAVztPTazA6fvHURnCTf6Lbw7Ok/YiyFZA../3Bed+Room+Bathroom.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/GWLzkN15D_s9AcxmnwKMS-yCogk/-HAyqg../3Bed+Room+Bedroom.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/08vKrzx5UUZLiaUnEeh3vVOgrgg/ev-txw../3Bed+Room+Kitchen+2nd.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/UpkvXUSsLCfVPq8j6o0Hwp7vuiQ/Xv5s6A../3Bed+Room+Living+room03.jpg',
               'https://soft.reelly.io/project/undefined'],
     'video': 'https://drive.google.com/file/d/1dDsu9W14o3wbg-rYZoOHAlHLfHwtQ77m/preview',
     'text': "Overview\nProject general facts\nCome home to a pocket of serenity. Golf Views offers you an impressive array of stylish one-, two, three- and four-bedroom apartments overlooking the 18-hole Championship golf course. It’s the perfect base in which to relax, explore and feel like you’re on holiday, every day.\nWhen you seek the city life, Golf Views is ideally located near the Dubai World Central peripheral road. Drop off your kids at school, go for lavish dinner in a nice hotel, or hit the shops - all in just a few minutes. What's more, the Al Maktoum International Airport and Expo 2020 are both less than a 10 minutes' drive away. You'll be living near the world's largest airport and the world's greatest show.\nWhen you move into Golf Views you become at one with nature. Away from the bustle and surrounded by lush green parks, you and your loved ones will enjoy the golf course, landscaped gardens, tree-lined boulevards, walking and bicycle trails, and so much more. You'll be hard-pressed to find a greener neighbourhood than the one around you.\nFinishing and materials\nFinished apartments\nKitchen and appliances\nNo information\nFurnishing\nNo\nLocation description and benefits\nEmaar South is a large-scale real estate development project situated in close proximity to the Dubai World Central (DWC) Al Maktoum International Airport, which is planned to become the largest airport in the world. The strategic location of Emaar South provides residents and businesses with excellent connectivity to major transportation hubs, including the airport, major highways, and Dubai's key commercial and residential areas.\nEmaar South is envisioned as a smart and sustainable community, integrating cutting-edge technologies and eco-friendly initiatives. The master plan incorporates green spaces, landscaped parks, cycling tracks, and walkways, encouraging an active and healthy lifestyle. The community also features a championship golf course, which adds to the recreational amenities available to residents and visitors.\nWithin Emaar South, there are planned retail centers, educational institutions, healthcare facilities, and a wide range of dining options. The community is designed to provide residents with easy access to everyday amenities, ensuring convenience and a high quality of life.",
     'point': {'Al Maktoum International Airport': '3.2', 'Motiongate Dubai': '20.5', 'Xpo Mall LLC': '22.1',
               'XO BEACH': '24.7', 'Fairgreen International School': '31', 'Downtown Dubai': '50.1'}, 'apartaments': [
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/6d19BRoD6FdF6f2Nm0YY8y7zmeo/VlnvZQ../3.png',
         'bedroom': '3 bedroom', 'aed_price': 'AED 1,990,000\n—\nAED 2,040,000', 'sqft': '1541\nsqft\n—\n1727\nsqft',
         'usd_price': '$537,300\n—\n$550,800', 'm2': '143.2\nm2\n—\n160.4\nm2'},
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/29wCnUFjb_30SZFOQ-Al9KgvUxU/nKagjg../4.png',
         'bedroom': '4 bedroom', 'aed_price': 'AED 3,200,000\n—\nAED 3,200,000', 'sqft': '2602\nsqft\n—\n2602\nsqft',
         'usd_price': '$864,000\n—\n$864,000', 'm2': '241.7\nm2\n—\n241.7\nm2'},
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/986DCB3CE7Rvgt86dAQ7wHLf738/25nCZg../1.png',
         'bedroom': '1 bedroom', 'aed_price': 'AED 0\n—\nAED 0', 'sqft': 'sqft\n—\nsqft', 'usd_price': '$0\n—\n$0',
         'm2': '0\nm2\n—\n0\nm2'},
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/rZxfC_R1I-lQ9xFamQy40OX0QBU/htBIOw../2.png',
         'bedroom': '2 bedroom', 'aed_price': 'AED 0\n—\nAED 0', 'sqft': '1000\nsqft\n—\n1312\nsqft',
         'usd_price': '$0\n—\n$0', 'm2': '92.9\nm2\n—\n121.9\nm2'}],
     'maps': 'C:\\Users\\user\\PycharmProjects\\dubai_reelly\\src\\files\\maps\\Golf Views.jpg',
     'cords': '24.861898,55.142256', 'status_update': False, 'exist_db': False},
    {'link': 'https://soft.reelly.io/project/general?projectid=105', 'name': 'Elvira', 'area': 'Dubai Hills',
     'devel': 'Emaar', 'price': '2210000', 'date': 'DEC 2026',
     'image': ['https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/0H9Je0oBW4OXucJhw0QV2_iyvmg/B71Log../8.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/5TiBSXBLA8Kd60eiZplZSdxLUg0/TlSEbw../9.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/c-QG6HrjuoJjCDMI20HvUy4-z-g/vlHJlw../10.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/bdTxri4O9gmaJaOK_o4pEKDjQR8/B7NYow../18.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/9OQgavS-XMmcRHJNnN5JkAkqOlo/8ujx2w../20.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/1_pSGeC3mqyos-OSonSmRDsN5-A/ymvYBw../DHE_ELVIRA_RENDERS9.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/7wTM2URoLfv-_awTEa2PfgpWmfE/hPHGew../DHE_ELVIRA_RENDERS12.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/jsyF9bgG7ZtYA-XaMgmj1drWfSE/ApexMw../DHE_ELVIRA_RENDERS14.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/snPaPB7KscnhHrEXQNq3zqJ0HTM/WXxsbQ../DHE_ELVIRA_RENDERS13.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/eI5BTuxODOKzC6HK_QC-Tt_UVOo/zmOrlQ../DHE_ELVIRA_RENDERS11.jpg',
               'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/3zaULFsdEqKN6UorL3MRMhztRn4/0kxVPw../DHE_ELVIRA_RENDERS8.jpg'],
     'video': 'https://drive.google.com/file/d/1mL7SIBCT-Cu0fJKpWLzVjU8zS3fpC_49/preview',
     'text': "Overview\nProject general facts\nElvira is a refuge of luxury living within Dubai Hills Estate, and it's only a few minutes away from the hustle and bustle of Downtown Dubai, where you'll find the city's business, financial, and retail emporia. This community has everything you might want, including spacious one- to three-bedroom homes, open green areas surrounded with trees and convenient proximity to a variety of educational, retail, medical, recreational, and social amenities\nFurnishing\nEach apartment's ultra-contemporary design complement the building's elegant, streamlined architecture guaranteeing the best park views. Come home to living spaces that exude sophistication, comfort with large windows welcoming in natural light and providing wonderful views of the park outside. A neutral material palette adding a warm ambiance. throughout the open-floor designed spaces.\nKitchen and appliances\nWithout kitchen appliances\nFurnishing\nUnfurnished\nLocation description and benefits\nDubai Hills Estate – the green heart of Dubai – is a first-of-its-kind destination. This masterfully planned, multi-purpose development forms an integral part of the Mohammed Bin Rashid City. Strategically situated between Downtown Dubai and Dubai Marina, flanked by Al Khail Road, the community offers easy access to the city’s most popular districts and attractions.",
     'point': {'GEMS International School': '2.9', 'Dubai Hills Mall': '4.4', 'Jumaira Beach': '11.4',
               'Downtown': '12.4'}, 'apartaments': [
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/GLzb2VOTR0LzUOt29VhLtrDzkOA/en-Naw../2.png',
         'bedroom': '2 bedroom', 'aed_price': 'AED 2,210,000\n—\nAED 2,290,000', 'sqft': '1063\nsqft\n—\n1142\nsqft',
         'usd_price': '$596,700\n—\n$618,300', 'm2': '98.8\nm2\n—\n106.1\nm2'},
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/BYz5sVU6IXLMYCMIn4URVouJBGk/0ONolA../3.png',
         'bedroom': '3 bedroom', 'aed_price': 'AED 3,690,000\n—\nAED 3,780,000', 'sqft': '1673\nsqft\n—\n1673\nsqft',
         'usd_price': '$996,300\n—\n$1,020,600', 'm2': '155.4\nm2\n—\n155.4\nm2'},
        {'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/1N8TuuN-wz-1Za6FVn1hl8MrGB8/JEETmw../1.png',
         'bedroom': '1 bedroom', 'aed_price': 'AED 0\n—\nAED 0', 'sqft': 'sqft\n—\nsqft', 'usd_price': '$0\n—\n$0',
         'm2': '0\nm2\n—\n0\nm2'}, {
            'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/u3Aq2mt1KADLca5h5m7oAx7H2nI/hgqI1A../Elvira+3+DP.png',
            'bedroom': '3 Bedroom Duplex', 'aed_price': 'AED 0\n—\nAED 0', 'sqft': 'sqft\n—\nsqft',
            'usd_price': '$0\n—\n$0', 'm2': '0\nm2\n—\n0\nm2'}, {
            'photo': 'https://xdil-qda0-zofk.m2.xano.io/vault/ZZLvFZFt/XJwsXxW4A8JDcVmvp_7frXGpVSM/OTnWBw../Elvira+3+TH.png',
            'bedroom': '3 Bedroom Townhouse', 'aed_price': 'AED 0\n—\nAED 0', 'sqft': 'sqft\n—\nsqft',
            'usd_price': '$0\n—\n$0', 'm2': '0\nm2\n—\n0\nm2'}],
     'maps': 'C:\\Users\\user\\PycharmProjects\\dubai_reelly\\src\\files\\maps\\Elvira.jpg',
     'cords': '25.10695,55.242516', 'status_update': False, 'exist_db': False}]
